export * from "./schoolData";
export * from "./departmentData";
export * from "./degreeData";
export * from "./teachingData";
export * from "./channelData";
export * from "./teacherData";
export * from "./courseData";
export * from "./classroomData";
export * from "./lectureData";
