export * from "./Docente";
export * from "./Corso";
export * from "./Gruppo";
export * from "./Laurea";
export * from "./Lezione";
export * from "./Aula";
export * from "./User";
export * from "./Account";
export * from "./Session";
